export const DRINK_COLS = 10
export const DRINK_ROWS = 6
/** Generic cup of coffee, for recipes added after the art was drawn. */
export const FALLBACK_DRINK_CELL = 60

/** Cell (1-based, row-major) in the 10×6 drink sprite for each recipe. Order and briefs: docs/drink-sprite-spec.md §3. */
export const DRINK_CELL: Record<string, number> = {
  affogato: 1,
  americano: 2,
  espresso: 3,
  'espresso-con-panna': 4,
  'espresso-romano': 5,
  'long-black': 6,
  lungo: 7,
  ristretto: 8,
  'cafe-au-lait': 9,
  breve: 10,
  latte: 11,
  mocha: 12,
  cappuccino: 13,
  cortado: 14,
  macchiato: 15,
  'flat-white': 16,
  'latte-macchiato': 17,
  piccolo: 18,
  'aeropress-inverted': 19,
  aeropress: 20,
  'drip-coffee-maker': 21,
  chemex: 22,
  'cold-brew': 23,
  'cowboy-coffee': 24,
  'french-press': 25,
  'japanese-iced-pour-over': 26,
  'moka-pot': 27,
  'v60-pour-over': 28,
  'blended-coffee-frappe': 29,
  'brown-sugar-shaken-espresso': 30,
  'dalgona-coffee': 31,
  'espresso-tonic': 32,
  'greek-frappe': 33,
  'iced-americano': 34,
  'iced-latte': 35,
  'iced-mocha': 36,
  'sweet-cream-cold-brew': 37,
  'bulletproof-coffee': 38,
  'vietnamese-coconut-coffee': 39,
  'vietnamese-iced-coffee': 40,
  'vietnamese-egg-coffee': 41,
  'cafe-bombon': 42,
  'cafe-con-leche': 43,
  'cafe-cubano': 44,
  'cafe-de-olla': 45,
  einspanner: 46,
  mazagran: 47,
  qahwa: 48,
  'swedish-egg-coffee': 49,
  'turkish-coffee': 50,
  'caramel-macchiato': 51,
  'honey-cinnamon-latte': 52,
  'maple-latte': 53,
  'mexican-mocha': 54,
  'pumpkin-spice-latte': 55,
  'vanilla-latte': 56,
  carajillo: 57,
  'espresso-martini': 58,
  'irish-coffee': 59,
}
