export const SPRITE_COLS = 8
export const SPRITE_ROWS = 6

/**
 * Cell (1-based, row-major) in the 8×6 ingredient sprite for every ingredient and equipment id.
 * Near-duplicates share a picture; the text label beside the icon tells them apart.
 * See docs/icon-sprite-spec.md for the drawing brief behind each cell.
 */
export const ICON_CELL: Record<string, number> = {
  'whole-beans': 1,
  'ground-coffee': 2,
  'dark-roast': 3,
  'espresso-beans': 3,
  'instant-coffee': 4,
  'cold-brew-concentrate': 5,
  'whole-milk': 6,
  'two-percent-milk': 6,
  'oat-milk': 7,
  'almond-milk': 7,
  'coconut-milk': 7,
  'heavy-cream': 8,
  'half-and-half': 8,
  'whipped-cream': 9,
  'sweetened-condensed-milk': 10,
  'evaporated-milk': 10,
  'vanilla-ice-cream': 11,
  butter: 12,
  egg: 13,
  sugar: 14,
  'brown-sugar': 15,
  piloncillo: 15,
  honey: 16,
  'maple-syrup': 16,
  'simple-syrup': 17,
  'vanilla-syrup': 17,
  'caramel-sauce': 18,
  'chocolate-sauce': 19,
  'dark-chocolate': 19,
  'cocoa-powder': 20,
  cinnamon: 21,
  'star-anise': 22,
  cardamom: 22,
  cloves: 22,
  nutmeg: 22,
  cayenne: 23,
  'pumpkin-puree': 24,
  'pumpkin-pie-spice': 24,
  'vanilla-extract': 25,
  orange: 26,
  lemon: 26,
  salt: 27,
  mint: 28,
  whiskey: 29,
  vodka: 29,
  'coffee-liqueur': 30,
  'licor-43': 30,
  water: 31,
  ice: 32,
  'tonic-water': 33,
  'sparkling-water': 33,
  'espresso-machine': 34,
  'moka-pot': 35,
  'french-press': 36,
  'pour-over': 37,
  chemex: 37,
  aeropress: 38,
  'drip-machine': 39,
  'phin-filter': 40,
  cezve: 41,
  'milk-frother': 42,
  whisk: 42,
  blender: 43,
  grinder: 44,
  kettle: 45,
  'gooseneck-kettle': 45,
  saucepan: 46,
  'cocktail-shaker': 47,
  'large-jar': 47,
  scale: 48,
}
